# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
  instance:
    hostname: medi-lab-lo-geek.herokuapp.com
    non-secure-port: 80
    prefer-ip-address: false

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://sql3.freemysqlhosting.net/sql3432004?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: sql3432004
    password: zeyiYGLEGA
    hikari:
      maximumPoolSize: 8
server:
  port: ${PORT:8080}

  jpa:
    # Replace by 'prod, faker' to add the faker context and have sample data loaded in production
    liquibase:
      contexts: prod
    mail:
      host: smtp.gmail.com
      port: 587
      username: superadmi.medilab@gmail.com
      password: logeek2021
      protocol: smtp
      tls: true
      properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com

    thymeleaf:
      cache: true
